### ISSUE TITLE
How to deal with select source files being recognized as having tabstop = 8

### ISSUE THREAD

**Issue by unphased** [ldx/vim-indentfinder#3]
Line 115: 

```
self.default_tabstop = int(vim.eval('&tabstop'))
```
I do have tabstop set to 4 in my vimrc. I am still seeing some files getting opened by default with 8 tabstop, which was going out of style before I was born.

So maybe its good to just replace this expression with a hardcoded 4. Then again probably similar logic holds for the rest of that mysterious python code... Well, I may stay up at night, but not over that.

**Comment by ldx** [comment]
What happens if you save the embedded python code as a python script, and run it on your input file? Does it say 4 in the output?

**Comment by unphased** [comment]
Well, I tried that, and had to go take "import vim" out and tweaked the vim
command call (to make it print out whatever "output" was), but I cannot
make the python script spit out any numbers or any output whatsoever.

**Comment by unphased** [comment]
BTW here is a file that gets 8 tabstop: https://github.com/tmux/tmux/blob/master/options-table.c

**Comment by ldx** [comment]
To me it says:

    $ python if.py Downloads/options-table.c
    mixed tab 8 space 2

And that seems to be correct, the file is full of tabs.

**Comment by unphased** [comment]
Hmm upon further inspection of the source code, I notice a few clues here and there that reveal that it indeed must require tabstop=8. See line 873 for the best example.

Well, I think this does mean that the algorithm is very much capable of picking out a proper value, and I was wrong to question it. 

The rest of the code still bugs me to look at it but this does seem to be how the author intended it to be.
